### ISSUE TITLE
Overflow hidden - issue for h2

### ISSUE THREAD

**Issue by jaredmurphy** [gittheking/gittheking.github.io#5]
The overflow: hidden CSS styling on the body tag is making the h2 text cut off. 

Suggest - add padding-bottom to the h2 or disable overflow: hidden on the h2

As is: (notice the p in "Developer")
![Imgur](http://i.imgur.com/b0kzwdS.png)

When I disabled "overflow: hidden" for the h2:
![Imgur](http://i.imgur.com/PUrP4yS.png)

**Comment by gittheking** [comment]
@jaredmurphy Good looks Jared much appreciated!

**Comment by gittheking** [comment]
Fixed with a simple line-height change.
